### ISSUE TITLE
Add support for modifying the sql settings in the `WithSqlServerPersistence` method

### ISSUE THREAD

**Issue by shawndewet** [akkadotnet/Akka.Hosting#105]
**Is your feature request related to a problem? Please describe.**
We are unable to modify the schema-name, table-name and auto-initialize values when I use the `.WithSqlServerPersistence()` extension method.

**Describe the solution you'd like**
We would like to be able to modify the schema-name, table-name and auto-initialize values for both the Journal and Snapshot tables when I use the `.WithSqlServerPersistence()` extension method.

**Describe alternatives you've considered**
We've tried adding a hocon config for this, like so:
```
.AddHocon(@"akka.persistence {
	                journal {
                        plugin = ""akka.persistence.journal.sql-server""
	                    sql-server {
                            schema-name = akka
                            auto-initialize = on
                        }
                    }
	                snapshot-store {
                        plugin = ""akka.persistence.snapshot-store.sql-server""
		                sql-server {
                            schema-name = akka
                            auto-initialize = on
                        }
                    }
                }");
```

But that does not work.  The tables are still initialized with `dbo` as the schema name.

**Comment by Aaronontheweb** [comment]
I guess we could add some more optional properties to do this - that wouldn't be too much of a stretcth.
