### ISSUE TITLE
Expose AskTimeout configuration in Akka.Hosting

### ISSUE THREAD

**Issue by wesselkranenborg** [akkadotnet/Akka.Hosting#106]
**Is your feature request related to a problem? Please describe.**
Akka.Hosting is created to 'get rid of' hocon configuration files to have a more seamless and easy model of setting up Akka.NET. Right now, in our solution, we only need hocon to configure the ask-timeout setting.

**Describe the solution you'd like**
Expose ask-timeout also via Akka.Hosting so that we can completely remove our .hocon files.

Akka.Hosting works really great so it helps if more options are getting exposed.

**Comment by PeterHageus** [comment]
It would also be nice to be able to set cluster related config, like minimum members.

**Comment by Aaronontheweb** [comment]
> It would also be nice to be able to set cluster related config, like minimum members.

This has been addressed
