### ISSUE TITLE
Add custom `System.Object` serializer and persistence default serializer peculiarity documentation

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/Akka.Hosting#141]
Persistence have its own default `System.Object` serializer settings here:

```
akka.persistence.journal-plugin-fallback.serializer = json
akka.persistence.snapshot-store-plugin-fallback.serializer = json
```
https://github.com/akkadotnet/akka.net/blob/3f7d3980fa45565abb824fe5f192f87c1bdde113/src/core/Akka.Persistence/persistence.conf#L119
https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Persistence/persistence.conf#L178

This is a big gotcha for people who does not know about this peculiarity and thinks that Akka persistence would use the custom `System.Object` serializer they configured with Akka, as shown in issue #127

This needs to be better documented

**Comment by Aaronontheweb** [comment]
I think we can close this now that https://github.com/akkadotnet/akka.net/issues/6389 is resolved
