### ISSUE TITLE
Add Support for `Akka.Persistence.Postgresql.Hosting`?

### ISSUE THREAD

**Issue by CumpsD** [akkadotnet/Akka.Hosting#25]
**Is your feature request related to a problem? Please describe.**

Akka.Hosting is a big step forward! Right now the out of the box persistence is SQL Server based. It would be nice for the people who run Postgresql to not have to run a separate SQL Server next to it.

**Describe the solution you'd like**

Create a `WithPostgresqlPersistence` extension method.

**Additional context**

Code for the extension methods for Sql Server: https://github.com/akkadotnet/Akka.Hosting/blob/dev/src/Akka.Persistence.SqlServer.Hosting/AkkaPersistenceSqlServerHostingExtensions.cs

The config is probably something like:

```csharp
Config journalConfiguration = $@"
  akka.persistence {{
    journal {{
      plugin = ""akka.persistence.journal.postgresql""

      postgresql {{
        class = ""Akka.Persistence.PostgreSql.Journal.PostgreSqlJournal, Akka.Persistence.PostgreSql""
        plugin-dispatcher = ""akka.actor.default-dispatcher""
        connection-timeout = 30s
        schema-name = public
        table-name = event_journal
        auto-initialize = off
        timestamp-provider = ""Akka.Persistence.Sql.Common.Journal.DefaultTimestampProvider, Akka.Persistence.Sql.Common""
        metadata-table-name = metadata
        stored-as = json
        sequential-access = off
        use-bigint-identity-for-ordering-column = on
        connection-string = ""{connectionString}""
      }}
    }}
  }}";

Config snapshotStoreConfig = $@"
  akka.persistence {{
    snapshot-store {{
      plugin = ""akka.persistence.snapshot-store.postgresql""

      postgresql {{
        class = ""Akka.Persistence.PostgreSql.Snapshot.PostgreSqlSnapshotStore, Akka.Persistence.PostgreSql""
        plugin-dispatcher = ""akka.actor.default-dispatcher""
        connection-timeout = 30s
        schema-name = public
        table-name = snapshot_store
        auto-initialize = off
        stored-as = json
        sequential-access = off
        connection-string = ""{connectionString}""
      }}
    }}
  }}";
```

**Comment by Aaronontheweb** [comment]
@CumpsD I strongly approve - best way to do this is to probably duplicate the SqlServer project structure and change the names / package dependencies accordingly.

Also, you could expose the `stored-as = json` and `sequential-access = off` as optional parameters on the methods if you were so inclined.

**Comment by CumpsD** [comment]
Done and done: https://github.com/akkadotnet/Akka.Hosting/pull/28 :)

**Comment by Aaronontheweb** [comment]
Excellent, thank you! We will probably move that library back into the Postgres repo once Akka.Hosting is "mature" - which will happen at the end of the 1.5 initial development effort (which is ongoing right now.) But for the time being, this is the right place for it to live while the community works on it.
