### ISSUE TITLE
MAUI support for Akka.Hosting (disable `IHostedService`)

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Hosting#289]
**Is your feature request related to a problem? Please describe.**

I spent some time chasing down a [.NET MAUI](https://dotnet.microsoft.com/en-us/apps/maui) user's issue getting `IRequiredActor<TKey>` to work correctly inside their application. Their `ActorRegistry` settings were correct and their code correctly binded Akka.NET to the `MauiAppBuilder` - the `IHost` equivalent for MAUI:

```csharp
public static MauiAppBuilder Akka(this MauiAppBuilder builder)
{
    builder.Services.AddAkka("MyActorSystem", akkaConfigurationBuilder =>
    {
        akkaConfigurationBuilder.PipeActor();
    });

    return builder;
}
```

Yet the `IRequiredActor<TKey>` injection doesn't work and throws an actor resolution error upon trying, even with Akka.Hosting v1.5.4+ - why is that?

This is because MAUI doesn't support `IHostedServices`: https://github.com/dotnet/maui/issues/2244

**Describe the solution you'd like**

Assuming that the rest of the core Akka DLL can even run on MAUI (i.e. there are no major AOT or other issues that would cause it to run not on the client), one solution we could try is configuring Akka.Hosting to run and launch all actors without the `IHostedService`. I think it might be possible to remove the `IHostedService` altogether without very little downside for regular users, possibly:

* We can still shut the `ActorSystem` down using the `IApplicationLifetime` and continuation `Task`s without needing the `IHostedService.StopAsync` method;
* We already start the `ActorSystem` prior to the `IHostedService.StartAsync` method;
* We already have a separate data structure for keeping track of what needs to be launched at startup - we could, in theory, just execute that as-is in the foreground with no code changes;
* We already blow up the foreground process and kill it if there are problems starting any of the actors or `Startup` tasks - we'd just be doing that with one less layer of indirection under this arrangement.

To implement this, we'd need an integration test that demonstrates Akka.NET failing to boot up under MAUI now - and we'd need to get that test to turn green by removing the `AkkaHostedService`.

**Describe alternatives you've considered**

Alternatively, rather than removing the `AkkaHostedService` we could add an extension method that starts up Akka.NET without the `IHostedService` - or we could add an explicit MAUI build target and using compiler directives that avoid the use of the `IHostedService` in MAUI only. Those would lower the risk of Akka.Hosting having adverse side-effects for existing users.

**Additional context**

**Comment by Arkatufus** [comment]
This is really not a bug, MAUI stopped "supporting" `Microsoft.Extensions.Hosting` last year, they didn't implement the interface properly in the first place.

https://github.com/dotnet/maui/issues/4393
https://github.com/dotnet/maui/pull/4505

**Comment by Aaronontheweb** [comment]
Resolved via https://github.com/akkadotnet/Akka.Hosting.Maui/releases/tag/1.5.6.1
