### ISSUE TITLE
Add an interface for the ActorRegistry class

### ISSUE THREAD

**Issue by SeanFarrow** [akkadotnet/Akka.Hosting#30]
It would be nice if the ActorRegistry derived from an non-Akka.Net interface, so that we could mock this when unit testing controllers.

**Comment by SeanFarrow** [comment]
OK, this is now done, so I will raise a PR in the next few days.

The only thing I was wondering, was why the actor system is being registered?

Unless I'm missing something, the whole idea is that the actor registry is used to retrieve actors at runtime. Given the actor system is created and then passed to the actor registry, does the actor system really need to be registered at all?

**Comment by Aaronontheweb** [comment]
Why not register it?

**Comment by SeanFarrow** [comment]
The only reason I wouldn’t register it is users not falling in to the ‘pit of success’ in terms of using the actor registry rather than the actor system itself.

**Comment by Aaronontheweb** [comment]
closed via https://github.com/akkadotnet/Akka.Hosting/pull/42

**Comment by Aaronontheweb** [comment]
> The only reason I wouldn’t register it is users not falling in to the ‘pit of success’ in terms of using the actor registry rather than the actor system itself.

I can still think of scenarios where it'd be useful to resolve the `ActorSystem` directly, such as scenarios where each request requires a dynamic "unit of work" actor managing a saga et al. I get your point though but I don't want to be _too_ opinionated.

**Comment by SeanFarrow** [comment]
Agreed, there are definitely reasons for not using the registry, although this should definitely be encouraged.

Thanks,
Sean.
