### ISSUE TITLE
IConfiguration To HOCON Adapter always converts all keys to lower-case

### ISSUE THREAD

**Issue by gunters63** [akkadotnet/Akka.Hosting#351]
**Version Information**
Version of Akka.NET? 1.5,12
Which Akka.NET Modules?

**Describe the bug**
In HOCON I can configure Akka.Net to use the Hyperion serializer like this:

````hocon
  actor {
    serializers {
      hyperion = "Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion"
    }
    serialization-bindings {
      "System.Object" = hyperion
    }
  }
````

I tried to move my HOCON configuration to ASP.NET IConfiguration (in appsettings.json).
Fist I had a problem with the dot character in "System.Object" because the HOCON adapter treats all keys as potentially dotted paths. I found out I can quote the key like this in my appsettings.json (this should probably be documented):

````json
{
  "akka": {
    "actor": {
      "serializers": {
        "hyperion": "Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion"
      },
      "serialization-bindings": {
        "\"System.Object\"": "hyperion"
      }
    }
  }
}
````

I have still the problem that the HOCON adapter converts all keys to lowercase (see ExpandKey in ConfigurationHoconAdapter.cs). I get the following warning at startup:

````
[WARNING][08.11.2023 08:29:24.190Z][Thread 0001][ActorSystem(EnsoBackend)] The type name for message/serializer binding 'hyperion' did not resolve to an actual Type: 'system.object'
````

and if I log the HCON config with `"log-config-on-start": true` I can see the problem:

<img width="225" alt="image" src="https://github.com/akkadotnet/Akka.Hosting/assets/90346/3f51dda3-f899-4867-9b43-d2e1cff33d9c">

**Comment by gunters63** [comment]
As a workaround I removed the hyperion stuff from appsettings.json for now and hardcoded it in Startup.cs:

````C#
.AddHocon(Configuration.GetSection("akka"), HoconAddMode.Prepend)
.AddHocon(string.Join(Environment.NewLine,
    @"akka.actor.serializers { hyperion = ""Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion""}",
    @"akka.actor.serialization-bindings { ""System.Object"" = hyperion}"), HoconAddMode.Prepend)
````

**Comment by mjalil** [comment]
I have the same problem

**Comment by Aaronontheweb** [comment]
Thanks, we'll look into this - not sure how I missed this issue earlier

**Comment by Arkatufus** [comment]
Added in 1.5.12.1, documentation can be read [here](https://github.com/akkadotnet/Akka.Hosting#special-characters-and-case-sensitivity)
