### ISSUE TITLE
Add the possibility to set the storage path of DData database in ShardOptions

### ISSUE THREAD

**Issue by montigab78** [akkadotnet/Akka.Hosting#431]
Hello, 
in my organization we use cluster sharding with DData storage.
Let'say we have this configuration:
 configurationBuilder =>
                {
                    configurationBuilder.WithShardRegion<TenantMarker>("tenants", (system, registry, resolver) =>
                    {
                       bla bla...
                    }, new TenantMessageRouter(),
                    new ShardOptions()
                    {
                        Role = TenantActorProps.ActorRole,
                        RememberEntities = true,
                        StateStoreMode = StateStoreMode.DData,
                        RememberEntitiesStore = RememberEntitiesStore.DData,
                    });
                }
When this is specified, a database named data.mdb gets created in my project_dir\ddata-projectname-webReplicator-9210 (in which 9210 is the port number).
However, when this service is installed in production as windows service, the same folder is created in C:\Windows\System32 
It would be useful to be able to configure the destination folder.

Thanks

**Comment by Arkatufus** [comment]
@montigab78 Sorry for taking so long to answer. We do actually have this option already, although it is kind of burried deep. The way you set the LMDB path is through `ShardOptions.DistributedData.Durable.Lmdb.Directory`. 

* If the directory ends with the word "ddata", the path will be appended with `"-{system_name}-{replicator-name}-{cluster-port}"`
* If set to a relative path, this will point to a directory relative to the working directory
