### ISSUE TITLE
LogConfigOnStart reports akka.actor.provider to be Akka.Actor.LocalActorRefProvider even though WithClustering is used 

### ISSUE THREAD

**Issue by Xeiotos** [akkadotnet/Akka.Hosting#472]
**Version Information**
Version of Akka.NET? 
Which Akka.NET Modules?

Akka.Cluster.Hosting 1.5.25

**Describe the bug**
LogConfigOnStart reports akka.actor.provider to be Akka.Actor.LocalActorRefProvider even though WithClustering is used

**To Reproduce**
See repo: https://github.com/Xeiotos/AkkaActorRefProviderConfigLogRepro

**Expected behavior**
I would expect the logged HOCON to reflect any configuration made through fluent API.
The logged hocon should report akka.actor.provider to be 'cluster' when WithClustering(..) is used.

**Actual behavior**
The logged hocon specifies akka.actor.provider : Akka.Actor.LocalActorRefProvider  even though clustering is configured using fluent API .WithClustering(..)

**Screenshots**
<img width="1118" alt="image" src="https://github.com/akkadotnet/Akka.Hosting/assets/2796952/245d49c2-126b-44a5-b19f-ee4bcc944280">

**Environment**
MacOS Sonoma, .NET 8

**Comment by Aaronontheweb** [comment]
This is a slight bug wit HOCON but not with Akka.Hosting - we use the C# configuration for loading the `IActorRefProvider`, i.e. [`ProviderSelection.Cluster`](https://getakka.net/api/Akka.Actor.ProviderSelection.Cluster.html). The HOCON gets ignored when that setting is present.
