### ISSUE TITLE
No way to disable `DData.Durable` with Akka.Hosting

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Hosting#512]
I can validate that this DOES disable DData from writing to disk:

```csharp
public static class DrawingSessionActorExtensions
{
    public static AkkaConfigurationBuilder AddDrawingSessionActor(this AkkaConfigurationBuilder builder,
        string clusterRoleName = ClusterConstants.DrawStateRoleName)
    {
        builder.WithShardRegion<DrawingSessionActor>("drawing-session",
                (system, registry, resolver) => s => resolver.Props<DrawingSessionActor>(s),
                new DrawingSessionActorMessageExtractor(), new ShardOptions()
                {
                    StateStoreMode = StateStoreMode.DData,
                    RememberEntities = true,
                    RememberEntitiesStore = RememberEntitiesStore.DData,
                    Role = clusterRoleName
                })
            // .WithDistributedData(options =>
            // {
            //     options.Durable = new DurableOptions() { Keys = [] }; // disable persistence
            // })
            .AddHocon("akka.cluster.sharding.distributed-data.durable.keys = []", HoconAddMode.Prepend);
        return builder;
    }
}
```

It looks like this is an Akka.Hosting issue with `options.Durable = new DurableOptions() { Keys = [] }; // disable persistence` not working as expected - and that's probably an easy fix.

_Originally posted by @Aaronontheweb in https://github.com/akkadotnet/akka.net/issues/7326#issuecomment-2460514548_

**Comment by Arkatufus** [comment]
`options.Durable` is not the right settings for this, this is the global DData setting ("akka.cluster.distributed-data"), not the global sharding distributed data settings ("akka.cluster.sharding.distributed-data"), those 2 settings are completely different.

**Comment by Arkatufus** [comment]
Added a new extension method API `.WithShardingDistributedData()` that actually applies to the correct HOCON setting here: https://github.com/akkadotnet/Akka.Hosting/pull/527
