### ISSUE TITLE
Add support for Akka.Logger.Serilog.Hosting

### ISSUE THREAD

**Issue by jblackburn21** [akkadotnet/Akka.Hosting#61]
**Is your feature request related to a problem? Please describe.**
I'm successfully using the hosting package, but I still have to configure Serilog in hocon, and ensure that the Akka.Logger.Serilog package is added to the project.

**Describe the solution you'd like**
Add a project for Akka.Logger.Serilog.Hosting that includes the dependency on Akka.Logger.Serilog, and has a builder extension method for WithSerilogLogger(string loglevel)

**Describe alternatives you've considered**
N/A

**Additional context**
A simple extension method could be added that sets the logger in the hocon

```csharp
public static class AkkaLoggerSerilogHostingExtensions
    {
        /// <summary>
        /// Configures Serilog logger.
        /// </summary>
        /// <param name="builder">The builder instance being configured.</param>
        /// <param name="loglevel">Specifies loglevel for <see cref="ActorSystem"/></param>
        /// <returns>The same <see cref="AkkaConfigurationBuilder"/> instance originally passed in.</returns>
        public static AkkaConfigurationBuilder WithSerilogLogger(this AkkaConfigurationBuilder builder, string loglevel)
        {
            if (!string.IsNullOrEmpty(loglevel))
            {
                builder.AddHocon($"akka {{ loglevel={loglevel},  loggers=[\"Akka.Logger.Serilog.SerilogLogger, Akka.Logger.Serilog\"]}}", HoconAddMode.Prepend);
            }

            return builder;
        }
    }
```

I have this code running, so let me know if you'd like me to send a PR.

**Comment by jblackburn21** [comment]
Thinking about this some more, it would make sense to add WithLogLevel to Akka.Hosting

```csharp
public static AkkaConfigurationBuilder WithLogLevel(this AkkaConfigurationBuilder builder, LogLevel logLevel) 
            => builder.AddHocon($"akka.loglevel={logLevel.StringFor()}", HoconAddMode.Prepend);
```

and have a new Serilog package just for setting the loggers

```csharp
public static class AkkaLoggerSerilogHostingExtensions
    {
        /// <summary>
        /// Configures Serilog logger.
        /// </summary>
        /// <param name="builder">The builder instance being configured.</param>
        /// <returns>The same <see cref="AkkaConfigurationBuilder"/> instance originally passed in.</returns>
        public static AkkaConfigurationBuilder WithSerilogLogger(this AkkaConfigurationBuilder builder) 
            => builder.AddHocon($"akka.loggers=[\"Akka.Logger.Serilog.SerilogLogger, Akka.Logger.Serilog\"]", HoconAddMode.Prepend);
    }
```

**Comment by Aaronontheweb** [comment]
We're considering doing a Microsoft.Extensions.Logging integration here instead, which would allow for the Serilog logging through that library to be instrumented as well. Not clear plans on how to do that as of yet, but it's been frequently requested.

**Comment by Arkatufus** [comment]
Added a draft PR on Microsoft.Extensions.Logging logger in #72, suggestions are welcome.

**Comment by Aaronontheweb** [comment]
Very nice
